import type { Metadata } from 'next'
import { fonts } from './fonts'
import { APP_NAME } from '@/config/constants'

export const metadata: Metadata = {
  title: APP_NAME,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={fonts.chakraPetch.variable}>{children}</body>
    </html>
  )
}
